version: "3.3"

services:
  app:
    container_name: men_assessment_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/men_assessment
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    container_name: men_assessment_mongo
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
    mongo-data:
