version: "3.3"

services:
  app:
    container_name: men_assessment_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    container_name: men_assessment_mongo
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
